#!/bin/csh
#
# Installs all .py files under the specified directory
# and sets appropriate permissions.

setenv INSTDIR	$1

if ( ! -d $INSTDIR ) then
	echo "$INSTDIR not a directory!"
	exit 1
endif

foreach i (`ls *.py`)
chmod ug+w $INSTDIR/$i
cp $i $INSTDIR
end
